stages:
  - build
  - deploy

build:
  stage: build
  image: python:3.8-alpine
  artifacts:
    paths:
      - dist/*
  before_script:
    - apk add build-base libffi-dev openssl-dev krb5-dev
    - pip install poetry
  script:
    - poetry build -n -v

deploy:
  stage: deploy
  image: python:3.8-alpine
  only:
    - tags
  variables:
    POETRY_HTTP_BASIC_GITLAB_USERNAME: "${PACKAGE_REGISTRY_USERNAME}"
    POETRY_HTTP_BASIC_GITLAB_PASSWORD: "${PACKAGE_REGISTRY_PASSWORD}"
  before_script:
    - apk add build-base libffi-dev openssl-dev
    - pip install poetry
    - poetry config repositories.gitlab "https://gitlab.cri.epita.fr/api/v4/projects/${CI_PROJECT_ID}/packages/pypi"
  script:
    - rm -f dist/*.whl
    - poetry publish -n -v -r gitlab
