stages:
  - build
  - deploy

.poetry-job: &poetry-job
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:3.11
  before_script:
    - "pip install poetry==1.6.1"

build:
  <<: *poetry-job
  stage: build
  artifacts:
    paths:
      - dist/*
  script:
    - apt-get update
    - apt-get install -y --no-install-recommends libkrb5-dev
    - poetry build -n -v

include:
  - template: SAST.gitlab-ci.yml

sast:
  stage: build

deploy:
  <<: *poetry-job
  stage: deploy
  only:
    - tags
  variables:
    POETRY_HTTP_BASIC_GITLAB_USERNAME: "${PACKAGE_REGISTRY_USERNAME}"
    POETRY_HTTP_BASIC_GITLAB_PASSWORD: "${PACKAGE_REGISTRY_PASSWORD}"
  script:
    - poetry config repositories.gitlab "https://gitlab.cri.epita.fr/api/v4/projects/${CI_PROJECT_ID}/packages/pypi"
    - rm -f dist/*.whl
    - poetry publish -n -v -r gitlab
