---
name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pipx install poetry || true
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libkrb5-dev bison krb5-kdc krb5-user krb5-admin-server
      - uses: actions/setup-python@v4
        with:
          python-version-file: "pyproject.toml"
          cache: "poetry"
      - run: poetry run make install
      - run: poetry run make test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pipx install poetry || true
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libkrb5-dev bison
      - uses: actions/setup-python@v4
        with:
          python-version-file: "pyproject.toml"
          cache: "poetry"
      - run: poetry run make install
      - run: poetry run make build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
